// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMx4gu2eF7qXuRXJkoxH8Jn59G__gP6JU',
    appId: '1:887837613876:web:20dc4bd77a63ccf38fcf61',
    messagingSenderId: '887837613876',
    projectId: 'pushnotifications-c2c7c',
    authDomain: 'pushnotifications-c2c7c.firebaseapp.com',
    storageBucket: 'pushnotifications-c2c7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVlQ9_cMullensje_g8rz1tM_3SJq6M54',
    appId: '1:887837613876:android:ddfc9417675e3e128fcf61',
    messagingSenderId: '887837613876',
    projectId: 'pushnotifications-c2c7c',
    storageBucket: 'pushnotifications-c2c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdozh2gBmJz14NfO_sKECGwef4i5CZE4Q',
    appId: '1:887837613876:ios:547bbd2a65e59e198fcf61',
    messagingSenderId: '887837613876',
    projectId: 'pushnotifications-c2c7c',
    storageBucket: 'pushnotifications-c2c7c.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdozh2gBmJz14NfO_sKECGwef4i5CZE4Q',
    appId: '1:887837613876:ios:cfd7bc47209477358fcf61',
    messagingSenderId: '887837613876',
    projectId: 'pushnotifications-c2c7c',
    storageBucket: 'pushnotifications-c2c7c.appspot.com',
    iosBundleId: 'com.example.firebaseNotifications.RunnerTests',
  );
}
